"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""



################### Changes done are in line 56 and 119 ###################

from pathlib import Path
import os
import ssl
import smtplib
from kombu import Queue
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5#=0gvb0h5k6bx%&nxienhu5*6uk=9fhtngkobi8mjz$)ecp1&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# TIME_ZONE =  'Asia/Kolkata'
TIME_ZONE =  'UTC'

USE_TZ = True

ALLOWED_HOSTS = ['*']

"""
    Need to run CalculateAssetHealthScore function before calculateAssetHealthHistory, these will be excluded in calculateAssetHealthHistory loop
    1) app.cron.CalculateAssetHealthScore: This will calculate asset health score and flag and save data to asset_health_master table only
    2) app.cron.calculateAssetHealthHistory: This will simple copy all asset data from asset_health_master to asset_health_history_master for asset timeline graph
"""

CRONJOBS = [
    # ///////// cron jobs for noraml data threshold and send mail /////////
    ('*/15 * * * *', 'app.thresholdFunctions.thresholdFunctions.checkThresholdCounter'),           # ///////// cron to run after every 1 min to check counter normal thresholds and send mail /////////
    ('*/8 * * * *', 'app.thresholdFunctions.thresholdFunctions.checkSignalStat'),       # ///////// cron to run after every 2 mins to check new data against saved threshold (both static and dynamic) and update counter table/////////
    
    #('* * * * *', 'app.thresholdFunctions.thresholdFunctions.checkThresholdCounter'),           # ///////// cron to run after every 5 min to check counter normal thresholds and send mail /////////
    #('*/10 * * * *', 'app.cron.DumpCounterDataToDatabaseV2'),     # ///////// cron to run after every 10 mins to check new data against saved threshold (both static and dynamic) and update counter table/////////

    # ///////// cron jobs for asset health score and status /////////
    ('5 0 * * *', 'app.cron.CalculateAssetHealthScore'),                                        # ///////// cron to run at 12:05 am to calculate asset health score and health flag /////////
    ('0 2 * * *', 'app.cron.calculateAssetHealthHistory'),                                     # ///////// cron to run at 12:20 am to calculate asset health history trend data /////////
    ('*/2 * * * *', 'app.cron.process_rms_batch'),   # ///////// cron to run after every 4 mins to check new data against saved threshold (diagnostic) and update counter table diagnostic /////////
    ('* * * * *', 'app.cron.checkSensorLiveStatus'),                                         # ///////// cron to run after every 15 mins to check new data ang update sensor status flag accordingly /////////
    
    # ///////// cron jobs for diagnostic data threshold and send mail /////////
    #('40 0 * * *', 'app.cron.CalculateThresholdForDiagnostics'),                                # ///////// cron to run at 12:40 am to calculate dynamic threshold for diagnostics (1x, 2x...etc) /////////
    #('*/3 * * * *', 'app.thresholdFunctions.diagnostics.checkDiagnosticThresholdCounter'),      # ///////// cron to run after every 3 mins to check counter diagnostic thresholds and send mail /////////
    #('*/4 * * * *', 'app.thresholdFunctions.diagnostics.CalculateCounterForDiagnostics'),   # ///////// cron to run after every 4 mins to check new data against saved threshold (diagnostic) and update counter table diagnostic /////////
    
    # ///////// cron jobs to check sensor status online/offline  /////////
]

# Application definition

INSTALLED_APPS = [
    'app.apps.AppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_crontab'
]


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 6379)],
#         }
#     }
# }

# CELERY_BEAT_SCHEDULE = {
#     'task-real': {
#         'task': 'realtime_task',
#         'schedule': 1 # this means, the task will run itself every second
#     },
# }


AUTH_USER_MODEL = 'app.Account'

REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    # )
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': []
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'app.customMiddleware.middleware.TokenAuthMiddleware', #activate only when all apis are updated ie token in headers
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / 'app' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'

ASGI_APPLICATION = 'dashboard.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Live data base
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'CONN_MAX_AGE': 120,
        }
    }


# testing data base password 'PASSWORD': 'postgres',
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'test_db',
#             'USER': 'postgres',
#             'PASSWORD': 'postgres',
#             'HOST': '65.0.69.79',
#             'PORT': 5432,
#             'CONN_MAX_AGE': 120,
#         }
#     }

# # local data base password 'PASSWORD': 'password123',
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'new_database',
#             'USER': 'postgres',
#             'PASSWORD': 'password123',
#             'HOST': 'localhost',
#             'PORT': 5432,
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtpout.secureserver.net'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''  # put abbott email here


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.abbott.com'
EMAIL_PORT = 25
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''


REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_REUSLT_BACKEND = CELERY_RESULT_BACKEND
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

CELERY_TASK_QUEUES = (
        Queue('defaultQueue'),
        Queue('wiredRmsQueue'),
        Queue('mailQueue')
        )

CELERY_TASK_ROUTES = {
        'app.task.saveRMSData' : {'queue': 'wiredRmsQueue'},
        'app.task.sendMailSingle'   : {'queue': 'mailQueue'}
        }

